name: Build and publish
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore Nugets
        run: nuget restore EntityMapper.sln

      - name: Pack EntityMapper
        run: nuget pack EntityMapper/EntityMapper.csproj -build -Prop Configuration=Release
      
      - name: Publish EntityMapper
        run: nuget push *.nupkg ${{secrets.NUGET_API_KEY}} -source  https://api.nuget.org/v3/index.json
